# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20190618_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
