# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='this-is-default-slug'),
            preserve_default=False,
        ),
    ]
